### ISSUE TITLE
'Seasons' OR Archive annual data from past campaigns

### ISSUE THREAD

**Issue by onlyjsmith** [disarm-platform/user-requests-and-feedback#6]
No question this is essential.

Has many implications, especially for changes in plans, form and geodata. We'll need to find a way to keep them in sync. Would be useful to think and talk this through together.

Depending on the approach we take, accessing past data may not be straightforward using the current interface by April, and we may need to find an alternative. Longer term we want to make all the data visible in the dashboard.

[Implementation note for dev team: could be an additional 'filter' level on the dashboard. Will need to limit the records being retrieved. Also, assume we will need plans for each season: implications e.g. how would we then view last season's coverage?]

### Proposed approach:
- admin user can edit a list of season or campaign 'start dates'
- users can choose from a dropdown of these start dates on the Monitor page; selecting one will set filters for the start and end dates and only responses from that period will be used on the Monitor page
- users are free to change the start and end date filters to see earlier/later dates
- users can select from a dropdown of 'Plans'; selecting one will use it for the denominator for the aggregations
- the default selection will be the most recent season start date, and the most recent plan
- Recorder users will not have to change anything, just keep recording observations

### Questions on approach
- [ ] any problems with persisting the filter state and adding a reset button?

### Implementation steps:
- [x] explore what 'seasons' are, gather more info
- [x] carry out rebuilding of config retrieval, improve test coverage
- [x] improve documentation and test coverage of existing data models
- [x] prepare and share wireframes for UI enhancements
- [x] prototype and test interactions with existing filters
- [x] adapt wireframes based on feedback
- [ ] implement client-side changes
- [x] implement server-side changes
- [ ] test and refine with beta testers (not field users)
- [ ] test and refine with users

**Comment by onlyjsmith** [comment]
### Admin
Admin can edit a list of _start dates_, each of which correspond to the first day of a season:
- add/remove dates
- works, but need to add validation to ensure valid date in correct format
- updates the instance configuration without requiring redeployment
<img width="1136" alt="screenshot 2018-04-09 15 05 57" src="https://user-images.githubusercontent.com/148280/38499667-9fafc616-3c08-11e8-88ee-23fbaf0cf517.png">
 
### Monitor user
Monitor user can select a season and a plan, and aggregations/maps/tables will update
- select a season's _start date_, which will set temporal filters (either using next season as an _until_ date or 'today' if it's the current season)
- select a plan from the list of plans, which loads the plan to use as denominator
- manually set any _start_ or _end_ date for temporal filtering
- reset to a default season (current) and plan (most recent)
- remove all filters and see every response (currently some performance implications we're aware of, and will work on)

<img width="1136" alt="screenshot 2018-04-09 15 06 11" src="https://user-images.githubusercontent.com/148280/38499696-ad22b934-3c08-11e8-99bc-12788e9b863c.png">

**Comment by onlyjsmith** [comment]
@sbabur few last client-side changes to make and we'll include a working prototype in next staging deploy

**Comment by onlyjsmith** [comment]
@sbabur please note that the current `start_dates` for each are random/made-up. You can edit on the Admin page, as above.

**Comment by onlyjsmith** [comment]
@sbabur ok to close?

**Comment by sbabur** [comment]
@onlyjsmith ok to close
